export enum JKDistrict {
  ANANTNAG = "Anantnag",
  BANDIPORA = "Bandipora",
  BARAMULLA = "Baramulla",
  BUDGAM = "Budgam",
  DODA = "Doda",
  GANDERBAL = "Ganderbal",
  JAMMU = "Jammu",
  KATHUA = "Kathua",
  KISHTWAR = "Kishtwar",
  KULGAM = "Kulgam",
  KUPWARA = "Kupwara",
  POONCH = "Poonch",
  PULWAMA = "Pulwama",
  RAJOURI = "Rajouri",
  RAMBAN = "Ramban",
  REASI = "Reasi",
  SAMBA = "Samba",
  SHOPIAN = "Shopian",
  SRINAGAR = "Srinagar",
  UDHAMPUR = "Udhampur",
}
